image:
  - Visual Studio 2019
  - macOS
  - Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: Ti46nPnZgFh0nRteU6ma0EhJnCTW7PaMn9hnnewZl4gBFPyRQnXNCwGog02+MRLX

install:
  - pip install -r requirements.txt

build_script:
  - flet pack app.py --name FletGPT --icon icon.png --product-name FletGPT --product-version "0.0.1" --copyright "Copyright (c) 2024, Vabiel"

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
#
for:
  -
    matrix:
      only:
        - image: Visual Studio 2019

    after_build:
      - 7z a FletGPT-windows.zip %CD%\dist\*.exe

    artifacts:
      - path: FletGPT-windows.zip

  #
  #   macOS package
  #
  -
    matrix:
      only:
        - image: macOS

    after_build:
      - tar -czvf FletGPT-macos.tar.gz -C dist FletGPT.app

    artifacts:
      - path: FletGPT-macos.tar.gz

  #
  #   Linux package
  #
  -
    matrix:
      only:
        - image: Ubuntu

    after_build:
      - tar -czvf FletGPT-linux.tar.gz -C dist FletGPT

    artifacts:
      - path: FletGPT-linux.tar.gz
